baseURL = 'https://rubyceng.github.io/'
languageCode = 'zh-cn'
title = "Ruby 随笔"
theme = "loveit"
# whether to use robots.txt
# 是否使用 robots.txt
enableRobotsTXT = true
# whether to use git commit log
# 是否使用 git 信息
enableGitInfo = true
# whether to use emoji code
# 是否使用 emoji 代码
enableEmoji = true
# 语言设置
defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = true


[params]
  # site default theme ["auto", "light", "dark"]
  # 网站默认主题 ["auto", "light", "dark"]
  defaultTheme = "auto"
  # public git repo url only then enableGitInfo is true
  # 公共 git 仓库路径，仅在 enableGitInfo 设为 true 时有效
  gitRepo = "https://github.com/rubyceng/Ruby-Blog.git"
  # date format
  # 日期格式
  dateFormat = "2006-01-02"



  # Author config
  # 作者配置
  [params.author]
    name = "Ruby"
    email = "rubyceng0326@gmail.com"
    link = "https://github.com/rubyceng"

  [params.header]
     # 页面头部导航栏标题配置
    [params.header.title]
      # URL of the LOGO
      # LOGO 的 URL
      # logo = "https://raw.githubusercontent.com/rubyceng/PicGo-Repo/main/Pic/Company202502051643835.png?token=BKKQCBFPISO4UQWHHEX7ZQTHUMSOK"
      # title name
      # 标题名称
      name = "Ruby 随笔"
      # you can add extra information before the name (HTML format is supported), such as icons
      # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
      post = ""
      # whether to use typeit animation for title name
      # 是否为标题显示打字机动画
      typeit = false


  # Home page config
  # 主页信息设置
  [params.home]
    # Home page profile
    # 主页个人信息
    [params.home.profile]
      enable = false
      


  # 文章页面配置
  # post page config
  [params.page]
    # 页面分享信息设置
    [params.page.share]
      enable = false
      Twitter = false
      Facebook = false
      Linkedin = false
      Whatsapp = false
      Pinterest = false
      Tumblr = false
      HackerNews = false
      Reddit = false
      VK = false
      Buffer = false

# 菜单配置
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 2

# 作者配置
[author]
  name = "Ruby"

# 分页配置
[pagination]
  disableAliases = false
  pagerSize = 10
  path = "page"