baseURL = 'https://example.org/'
languageCode = 'zh-cn'
title = 'Ruby Blog'

# 修改主题名称为文件夹名
theme = "hugo-PaperMod"

# 添加一些基本参数
[params]
  defaultTheme = "auto"
  ShowShareButtons = true
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 20