name: Deploy Hugo Site

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false # 明确不使用 submodules

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.123.0" # 使用稳定版本
          extended: true

      - name: Clean theme directory
        run: |
          rm -rf themes/LoveIt themes/loveit

      - name: Install theme
        run: |
          git clone https://github.com/dillonzq/LoveIt.git themes/loveit

      - name: Build
        run: |
          ls -la themes/loveit
          hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: rubyceng/rubyceng.github.io
          publish_dir: ./public
          commit_message: "Deploy: ${{ github.event.head_commit.message }}"
          force_orphan: true
